# FROM node:18.18.0-alpine

# WORKDIR /app

# # Copy package files
# COPY package.json package-lock.json* ./

# # Install dependencies
# RUN npm ci

# # Copy the rest of the code
# COPY . .

# ENV NODE_ENV=development
# EXPOSE 3000

# CMD ["npm", "run", "dev"]
# Use official Node.js base image as build stage
FROM node:18.18.0-alpine AS base

WORKDIR /app

COPY package.json package-lock.json* ./
RUN npm ci

COPY . .

RUN npm run build

# Runner stage (production image)
FROM node:18.18.0-alpine AS runner

WORKDIR /app

ENV NODE_ENV=production

COPY --from=base /app/public ./public
COPY --from=base /app/.next ./.next
COPY --from=base /app/node_modules ./node_modules
COPY --from=base /app/package.json ./package.json

EXPOSE 3000

CMD ["npm", "run", "start"]
