"""updated models

Revision ID: 1c33c3f12f3d
Revises: 2116dad5e395
Create Date: 2025-04-28 06:26:08.726674

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '1c33c3f12f3d'
down_revision = '2116dad5e395'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
