"""empty message

Revision ID: 2631ad713c99
Revises: 78b7641e0965
Create Date: 2025-06-19 12:52:34.314865

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '2631ad713c99'
down_revision = '78b7641e0965'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('viewingrequest', sa.Column('message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('viewingrequest', 'message')
    # ### end Alembic commands ###
