"""update field

Revision ID: 34e5ca1f248d
Revises: bbd0fb07ba49
Create Date: 2025-04-29 11:18:07.136164

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '34e5ca1f248d'
down_revision = 'bbd0fb07ba49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_user_is_approved'), 'user', ['is_approved'], unique=False)
    op.create_index(op.f('ix_user_role'), 'user', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_role'), table_name='user')
    op.drop_index(op.f('ix_user_is_approved'), table_name='user')
    # ### end Alembic commands ###
