"""empty message

Revision ID: 5365269226b1
Revises: 73dfed0a5591
Create Date: 2025-06-21 06:20:59.267330

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '5365269226b1'
down_revision = '73dfed0a5591'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
