"""empty message

Revision ID: 73dfed0a5591
Revises: 2631ad713c99
Create Date: 2025-06-21 06:17:30.442692

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '73dfed0a5591'
down_revision = '2631ad713c99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('propertyview_user_id_fkey', 'propertyview', type_='foreignkey')
    op.create_foreign_key(None, 'propertyview', 'user', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_constraint('review_user_id_fkey', 'review', type_='foreignkey')
    op.create_foreign_key(None, 'review', 'user', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_constraint('viewingrequest_user_id_fkey', 'viewingrequest', type_='foreignkey')
    op.create_foreign_key(None, 'viewingrequest', 'user', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_constraint('wishlist_user_id_fkey', 'wishlist', type_='foreignkey')
    op.create_foreign_key(None, 'wishlist', 'user', ['user_id'], ['user_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wishlist', type_='foreignkey')
    op.create_foreign_key('wishlist_user_id_fkey', 'wishlist', 'user', ['user_id'], ['user_id'])
    op.drop_constraint(None, 'viewingrequest', type_='foreignkey')
    op.create_foreign_key('viewingrequest_user_id_fkey', 'viewingrequest', 'user', ['user_id'], ['user_id'])
    op.drop_constraint(None, 'review', type_='foreignkey')
    op.create_foreign_key('review_user_id_fkey', 'review', 'user', ['user_id'], ['user_id'])
    op.drop_constraint(None, 'propertyview', type_='foreignkey')
    op.create_foreign_key('propertyview_user_id_fkey', 'propertyview', 'user', ['user_id'], ['user_id'])
    # ### end Alembic commands ###
