"""empty message

Revision ID: 78b7641e0965
Revises: e1f3344b278e
Create Date: 2025-06-10 07:14:10.847064

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '78b7641e0965'
down_revision = 'e1f3344b278e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('property', 'rating',
               existing_type=sa.NUMERIC(precision=2, scale=2),
               type_=sa.Numeric(precision=4, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('property', 'rating',
               existing_type=sa.Numeric(precision=4, scale=2),
               type_=sa.NUMERIC(precision=2, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###
