"""update constraint

Revision ID: c2683f3d9c99
Revises: 1c33c3f12f3d
Create Date: 2025-04-28 07:33:10.138723

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c2683f3d9c99'
down_revision = '1c33c3f12f3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('property', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('property', 'rating',
               existing_type=sa.NUMERIC(precision=3, scale=2),
               type_=sa.Numeric(precision=2, scale=2),
               existing_nullable=True)
    op.create_index(op.f('ix_property_user_id'), 'property', ['user_id'], unique=False)
    op.create_unique_constraint('uq_property_feature', 'propertyfeature', ['property_id', 'feature_id'])
    op.drop_constraint('propertyfeature_property_id_fkey', 'propertyfeature', type_='foreignkey')
    op.create_foreign_key(None, 'propertyfeature', 'property', ['property_id'], ['property_id'], ondelete='CASCADE')
    op.drop_constraint('propertylocation_property_id_fkey', 'propertylocation', type_='foreignkey')
    op.create_foreign_key(None, 'propertylocation', 'property', ['property_id'], ['property_id'], ondelete='CASCADE')
    op.drop_constraint('propertymedia_property_id_fkey', 'propertymedia', type_='foreignkey')
    op.create_foreign_key(None, 'propertymedia', 'property', ['property_id'], ['property_id'], ondelete='CASCADE')
    op.drop_constraint('propertypricing_property_id_fkey', 'propertypricing', type_='foreignkey')
    op.create_foreign_key(None, 'propertypricing', 'property', ['property_id'], ['property_id'], ondelete='CASCADE')
    op.create_index(op.f('ix_propertyview_property_id'), 'propertyview', ['property_id'], unique=False)
    op.create_index(op.f('ix_propertyview_user_id'), 'propertyview', ['user_id'], unique=False)
    op.drop_constraint('propertyview_property_id_fkey', 'propertyview', type_='foreignkey')
    op.create_foreign_key(None, 'propertyview', 'property', ['property_id'], ['property_id'], ondelete='CASCADE')
    op.create_index(op.f('ix_review_property_id'), 'review', ['property_id'], unique=False)
    op.create_index(op.f('ix_review_user_id'), 'review', ['user_id'], unique=False)
    op.drop_constraint('review_property_id_fkey', 'review', type_='foreignkey')
    op.create_foreign_key(None, 'review', 'property', ['property_id'], ['property_id'], ondelete='CASCADE')
    op.create_index(op.f('ix_viewingrequest_property_id'), 'viewingrequest', ['property_id'], unique=False)
    op.create_index(op.f('ix_viewingrequest_user_id'), 'viewingrequest', ['user_id'], unique=False)
    op.drop_constraint('viewingrequest_property_id_fkey', 'viewingrequest', type_='foreignkey')
    op.create_foreign_key(None, 'viewingrequest', 'property', ['property_id'], ['property_id'], ondelete='CASCADE')
    op.create_index(op.f('ix_wishlist_property_id'), 'wishlist', ['property_id'], unique=False)
    op.create_index(op.f('ix_wishlist_user_id'), 'wishlist', ['user_id'], unique=False)
    op.drop_constraint('wishlist_property_id_fkey', 'wishlist', type_='foreignkey')
    op.create_foreign_key(None, 'wishlist', 'property', ['property_id'], ['property_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wishlist', type_='foreignkey')
    op.create_foreign_key('wishlist_property_id_fkey', 'wishlist', 'property', ['property_id'], ['property_id'])
    op.drop_index(op.f('ix_wishlist_user_id'), table_name='wishlist')
    op.drop_index(op.f('ix_wishlist_property_id'), table_name='wishlist')
    op.drop_constraint(None, 'viewingrequest', type_='foreignkey')
    op.create_foreign_key('viewingrequest_property_id_fkey', 'viewingrequest', 'property', ['property_id'], ['property_id'])
    op.drop_index(op.f('ix_viewingrequest_user_id'), table_name='viewingrequest')
    op.drop_index(op.f('ix_viewingrequest_property_id'), table_name='viewingrequest')
    op.drop_constraint(None, 'review', type_='foreignkey')
    op.create_foreign_key('review_property_id_fkey', 'review', 'property', ['property_id'], ['property_id'])
    op.drop_index(op.f('ix_review_user_id'), table_name='review')
    op.drop_index(op.f('ix_review_property_id'), table_name='review')
    op.drop_constraint(None, 'propertyview', type_='foreignkey')
    op.create_foreign_key('propertyview_property_id_fkey', 'propertyview', 'property', ['property_id'], ['property_id'])
    op.drop_index(op.f('ix_propertyview_user_id'), table_name='propertyview')
    op.drop_index(op.f('ix_propertyview_property_id'), table_name='propertyview')
    op.drop_constraint(None, 'propertypricing', type_='foreignkey')
    op.create_foreign_key('propertypricing_property_id_fkey', 'propertypricing', 'property', ['property_id'], ['property_id'])
    op.drop_constraint(None, 'propertymedia', type_='foreignkey')
    op.create_foreign_key('propertymedia_property_id_fkey', 'propertymedia', 'property', ['property_id'], ['property_id'])
    op.drop_constraint(None, 'propertylocation', type_='foreignkey')
    op.create_foreign_key('propertylocation_property_id_fkey', 'propertylocation', 'property', ['property_id'], ['property_id'])
    op.drop_constraint(None, 'propertyfeature', type_='foreignkey')
    op.create_foreign_key('propertyfeature_property_id_fkey', 'propertyfeature', 'property', ['property_id'], ['property_id'])
    op.drop_constraint('uq_property_feature', 'propertyfeature', type_='unique')
    op.drop_index(op.f('ix_property_user_id'), table_name='property')
    op.alter_column('property', 'rating',
               existing_type=sa.Numeric(precision=2, scale=2),
               type_=sa.NUMERIC(precision=3, scale=2),
               existing_nullable=True)
    op.alter_column('property', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
