"""add id_card

Revision ID: c619a26c74e7
Revises: 34e5ca1f248d
Create Date: 2025-05-10 14:41:12.483288

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c619a26c74e7'
down_revision = '34e5ca1f248d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('revokedtoken', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('revokedtoken', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True)
    op.drop_column('revokedtoken', 'revoked_at')
    op.add_column('user', sa.Column('id_card_url', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'id_card_url')
    op.add_column('revokedtoken', sa.Column('revoked_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.alter_column('revokedtoken', 'expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('revokedtoken', 'created_at')
    # ### end Alembic commands ###
