"""update user deletion cascade property logic

Revision ID: e1f3344b278e
Revises: c619a26c74e7
Create Date: 2025-05-12 09:44:22.314283

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'e1f3344b278e'
down_revision = 'c619a26c74e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('property_user_id_fkey', 'property', type_='foreignkey')
    op.create_foreign_key(None, 'property', 'user', ['user_id'], ['user_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'property', type_='foreignkey')
    op.create_foreign_key('property_user_id_fkey', 'property', 'user', ['user_id'], ['user_id'])
    # ### end Alembic commands ###
